---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bds
spec:
  storageClassName: bds
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bds-pv-volume
  labels:
    type: local
spec:
  storageClassName: bds
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/bds"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bds
  labels:
    app: bds
spec:
  replicas: 1
  template:
    metadata:
      name: bds
      labels:
        app: bds
    spec:
      containers:
        - name: bds
          image: itzg/minecraft-bedrock-server
          imagePullPolicy: Always
          tty: true
          stdin: true
          env:
            - name: EULA
              value: "TRUE"
            - name: GAMEMODE
              value: "survival"
            - name: DIFFICULTY
              value: "normal"
            - name: ALLOW_CHEATS
              value: "true"
          volumeMounts:
            - mountPath: /data
              name: data
          livenessProbe:
            exec:
              command: 
                - /usr/local/bin/mc-monitor
                - status-bedrock 
                - --host 
                - 127.0.0.1
                - --port
                - "19132"
            initialDelaySeconds: 120
            timeoutSeconds: 10
            failureThreshold: 10
          readinessProbe:
            exec:
              command: 
                - /usr/local/bin/mc-monitor
                - status-bedrock 
                - --host 
                - 127.0.0.1
                - --port 
                - "19132"
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bds
  selector:
    matchLabels:
      app: bds
---
apiVersion: v1
kind: Service
metadata:
  name: bds
spec:
  selector:
    app: bds
  ports:
    - port: 19132
      nodePort: 19132
      protocol: UDP
      name: minecraft
  type: NodePort 
